project:
  type: website

website:
  title: "Simon Steiger"
  # site-url: 
  description: "R Shiny developer at Karolinska Universitetssjukhuset"
  # favicon: 
  page-navigation: true
  back-to-top-navigation: true
  # comments:
  #   utterances:
  #     repo: simonsteiger/itsme
  #     label: utterances
  #     theme: body-light
  #     issue-term: title
  
  navbar:
  # logo:
    tools:
    - icon: github
      href: https://www.github.com/simonsteiger/itsme
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about/index.qmd
      - text: Blog
        href: blog/index.qmd

format:
  html:
    theme: [cosmo, assets/index.scss]
    toc: true
    highlight-style: a11y
    code-link: true

execute:
  freeze: auto

jupyter: julia-1.9



